### PR TITLE
added move to First and Last buttons

### PR DESCRIPTION
**Pull request by ncolletti**
Essentially just adding a move to top and move to bottom button along side the current move buttons.

**Use case:** With many redirect rules and I found I would want to visually group them together for a certain project and the existing rules were far away on the list and I needed to bring them to the top. It was cumbersome to click many many times, so instead the user can just click once. Also, if the user needs just to move something out of view, without deleting it, they can use these buttons.  

I am also working on a PR for **groupings**, which will allow the user to select multiple rules and move them around together. Let me know if this would be of interest to continue on.

There are a bunch of small linting changes here, apologies and let me know if you want me to fix that.

### CODE REVIEW

**Comment by einaregilsson** [comment]
Ok, interesting. Could you post a screenshot of what it looks like with the new buttons?

As for grouping the rules together, what kind of a UI are you thinking for it? I don't want the UI to feel too cluttered.

**Comment by ncolletti** [comment]
Here is an image of the new buttons:
Screen Shot 2020-01-31 at 1 50 34 PM

Here is the input checkbox, I tried to style it a bit to fit the ascetic. Thoughts are that a user would select a few and then the navigation buttons would move each of them accordingly. Currently only have it setup for nav buttons, but if you are interested I can try to get it working for the others. (enable, disable, edit, duplicate)
Screen Shot 2020-01-31 at 1 52 43 PM

**Comment by einaregilsson** [comment]
Hmmm, I'm a bit conflicted about this one. I can see that it's useful for power users with lots of redirects, but it makes things more confusing for casual users, with more buttons, and checkboxes that is hard to understand what are for. If you select multiple redirects, can you delete multiple ones together, or is it just for moving to top? It's not obvious from just seeing a checkbox.

I will merge it in if it's hidden by default, the arrow buttons and the checkboxes. Add another button, "Organize" between Export and Help and when you click it you get a little div showing that tells you: "Use ⟱ to move a redirect to the bottom, ⟰ to move to the top, and use the checkboxes to select multiple redirects and move them together." And then the buttons and checkboxes become visible. When you click the Organize button you can just add a "organize-mode" to the <body> element and use that to show/hide the buttons and checkboxes.

Thoughts?

**Comment by ncolletti** [comment]
Cool! Ya that makes sense. I've pushed an update for you to check out.

It contains completed work for; the display message, organize button, along with the hide/show mechanics. The Organize button currently will stay highlighted while the Organize mode is active to better notify the user that is why they are seeing these features. Screenshot below as well.

The selecting of groups will work on all buttons except 'Edit' - since this spawns a new window with specific details for that Redirect. Still work to be done with that, will update when I can.

image

**Comment by einaregilsson** [comment]
Cool! Excellent work. I'll merge it in now, will try to get out a release sometime in the coming weeks. 🙂

**Pull request merged**
