### PR TITLE
Fix storage sync checkbox initial state

### LINKED ISSUE #201: Sync option unchecked even when sync is enabled
To reproduce, make sure that rules are few enough; I have only two short ones. Just check the “Enable Storage Sync” and see the notification “Sync is enabled!” now refresh the page. The checkbox become un-checked again.

Issue is at

https://github.com/einaregilsson/Redirector/blob/0772e5987336c3c469a8ec849ac3f54aab81bf33/js/redirectorpage.js#L46

It is checking `#storage-sync-option`, which is a label, not an `input`; see

https://github.com/einaregilsson/Redirector/blob/0772e5987336c3c469a8ec849ac3f54aab81bf33/redirector.html#L198

I guess simply appending `input` to the selector would work.

### LINKED ISSUE #303: Storage Sync Check Box Having Opposite Effect
Checking "Enable Storage Sync" actually disables sync instead of enabling it, and unchecking the box enables it. I encountered this in Chrome for both MacOS and Windows.

image

### PR DESCRIPTION
**Pull request by Victor4X**
Fixes #201
Fixes #303

As mentioned in #201 this was indeed the only required change.
Everything is now working as expected in my testing

### CODE REVIEW

**Comment by pointydev** [comment]
Would be great if this was pulled in as I just installed the extension and ran into this exact issue.

**Comment by maximedrouhin** [comment]
Hi @Gitoffthelawn! Since it seems you are now in charge of managing the project (https://github.com/einaregilsson/Redirector/issues/329#issuecomment-1384906484), would you mind accepting this minor PR? In addition to the author, I also confirmed locally that everything works.

**Comment by Gitoffthelawn** [comment]
@maximedrouhin Yes, sounds good.  I will hopefully get to it very soon.  I need to take a look at a few branching techniques on GitHub.  Are you an expert in that area by any chance?  It may be helpful to have someone to ask if I have questions.

**Comment by maximedrouhin** [comment]
I'm far from being an expert, but I can still try to give you advice based on my limited knowledge.
Basically, to handle contributions and to keep things working well, I think these are the first three levels:
---
**Level 1: You basically just review PRs, and maybe get a bit of assistance to do it.**
You let volunteers suggest features and report bugs (via the Issues tab in GitHub), and you let volunteers improve the code base via Pull Requests. You can also participate in this.
Your role is to check Pull Requests:
- You clone the repo that the volunteer wants to merge into this repo
- You check if you can use the extension normally in general
- You have a look to the code changes and check if you understand them and if everything seems good - directly in GitHub for example. You can use ChatGPT or similar to explain changes to you if you want.
- You check if you can use the extension normally in the specific areas where code changes were made
If everything looks fine, you can merge the PR.
You can also identify people that you trust and let them do this for you after ensuring that they understood that they have to check the code changes and test the extension before merging.
---
**Level 2: You add automated checks to ensure things always work well in the master branch.**
You can automate the "check that the extension is working" part to a certain extent using Actions. I don't know that much about it, but apparently you can have automated checks that ensure that things work correctly, and block merging before the checks pass.
This can speed up reviewing PRs, and most importantly ensure that everything is always working well.
---
**Level 3: More complex way to handle branches?**
You could have a complex way to handle branches, but I think this is more useful for very big projects with many active contributors. In this case, things work fine by default: You have a master branch that is always up-to-date and where the extension works well, and volunteers work on a copy of the repo and do a PR when they think everything works well.
---
There is still the question of how to deploy the extension to Firefox and Chrome, and I don't know much about this. I just know you should use the "Releases" feature of Github to tag the current commit with a version number (https://github.com/einaregilsson/Redirector/tags) when you think the extension is ready for production. 
---
It might be a good idea to create a Discord server for this project and link it in the README and in the description of the extension in both extension stores (Chrome and Firefox). This way you'll be able to get help easily, and people who are interested in helping this extension can chat about it.

**Comment by maximedrouhin** [comment]
@Gitoffthelawn (just in case you didn't get notified)

**Comment by Gitoffthelawn** [comment]
@maximedrouhin Thank you for your helpful note Maxime.  I just received it, due to more than expected going on here.  I'm hoping to block out 2-3 hours of my time to focus and figure out a good plan.  I'll likely have a couple specific questions on which you may be able to advise.

After some more administrative stuff, the next main course of action is to release a version with this patch and a couple other tweaks that should (hopefully) not result in any regressions.

**Comment by maximedrouhin** [comment]
> @maximedrouhin Thank you for your helpful note Maxime. I just received it, due to more than expected going on here. I'm hoping to block out 2-3 hours of my time to focus and figure out a good plan. I'll likely have a couple specific questions on which you may be able to advise.
> 
> After some more administrative stuff, the next main course of action is to release a version with this patch and a couple other tweaks that should (hopefully) not result in any regressions.

Don't hesitate to ask questions to me, I'll try to answer as best I can! You can hit me up on Discord (username kodemax), or another app, just tell me which one and your username. I should be a lot more reactive this way 😅

Good luck with everything!

**Comment by maximedrouhin** [comment]
> @maximedrouhin Thank you for your helpful note Maxime. I just received it, due to more than expected going on here. I'm hoping to block out 2-3 hours of my time to focus and figure out a good plan. I'll likely have a couple specific questions on which you may be able to advise.
> 
> After some more administrative stuff, the next main course of action is to release a version with this patch and a couple other tweaks that should (hopefully) not result in any regressions.

@Gitoffthelawn Don't hesitate to ask questions to me, I'll try to answer as best I can! You can hit me up on Discord (username kodemax), or another app, just tell me which one and your username. I should be a lot more reactive this way 😅

Good luck with everything!

**Comment by Gitoffthelawn** [comment]
@maximedrouhin Thank you for the kind offer Maxime.  I've made a note to contact you if I run into any snags or have any questions.  Thanks again.

**Comment by piejanssens** [comment]
@Gitoffthelawn can we get this in, please? It's almost a year for a one-liner review :-)

**Review by Gitoffthelawn — APPROVED** [review]

**Pull request merged**
