### PR TITLE
Add toolbar icon

### PR DESCRIPTION
**Pull request by Frogomeli**
For issue #5

### CODE REVIEW

**Comment by Gitoffthelawn** [comment]
Thanks!  I have to ask... why the choice of tootbarImg?

**Comment by Frogomeli** [comment]
Sorry a spelling error

**Comment by Gitoffthelawn** [comment]
LOL.  No problem!

Einer, if/when you merge this, I think there is also one outstanding pull (font related) from the recent UI improvements, IIRC.

**Comment by einaregilsson** [comment]
Thanks, have merged. The icon looks pretty horrible though next to the built in ones, with its non anti-aliased R and banned sign. If someone feels like making better images I'd put them in. Also, the button doesn't seem to be highlighted when I hover over it, don't know why. Anyway, it works :)

**Comment by einaregilsson** [comment]
@Gitoffthelawn I don't see any open pull requests?

**Comment by Gitoffthelawn** [comment]
@einaregilsson (Side issue [not toolbar button]: I think it was a merged pull that just wasn't uploaded to AMO.  It got included in the AMO update just made available... all is good.)

**Comment by Gitoffthelawn** [comment]
Uh oh... just tried the new toolbar button.  Here's what I see:

1. When the toolbar button is placed in the navbar (the standard toolbar), the toggle works, but there is no visual indication that a toggle took place (the on and off states look identical).

2. When the toolbar button is placed in the app menu (aka hamburger menu), the toggle works, but:
  a. there is no visual indication that a toggle took place.
  b. the "Redirector" text appears to the right of the icon instead of below it, preventing normal layouts and flow.
  c. the Redirector button does not look like any other buttons.  All the other buttons are squares that fit in the app menu panel nicely, but the Redirector toolbar button does not have the same shape/look/feel as any of the other buttons.

**Comment by Frogomeli** [comment]
Yes, there is a little bug.
Place the button in navbar then restart Firefox and then the visual indication should work.

**Comment by Gitoffthelawn** [comment]
Does that fix the second item above as well?

**Pull request merged**
